# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=20)),
                ('date_completed', models.DateTimeField(default=django.utils.timezone.now)),
                ('reps', models.IntegerField(default=1)),
            ],
        ),
    ]
